
name: Input_workflow
on: lint
jobs: 
    lint-job:
        runs-on: ubuntu-latest
        steps:
            - name: Install-lint
              uses: action/checkout@v0.8.19
            - name: install lint
              uses: action/setup-node@0.8.19
              with: 
                node-version: 0.8.19
            - name: install dependencies 
              run: npm i -g lint
            - name: Run npm i -g lint
              run: test npm i -g lint 
    output-job:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "{{ tolint(lint)}}"
